### ISSUE TITLE
change default mode to do a `readat(2)` call for accessing the data file

### ISSUE THREAD

**Issue by bobby-stripe** [bpowers/bit#2]
we should still use mmap for the index file, as we expect that to fit in our working set, but should read the data from disk with a single `readat(2)` call, to avoid tying up a Go `p` ([ref](https://www.ardanlabs.com/blog/2018/08/scheduling-in-go-part2.html)) while the mmap memory access stalls in a page-fault reading the data from EBS

**Comment by bpowers** [comment]
fixed as of 91ac70be1bede12b097ef41ec2f884f011c8c250 , with a `bit.WithMMap(true)` option available
